#!/usr/bin/env bash

# read script environ argument
ENVIRON=$1
if ! [[ ${ENVIRON} =~ dev|beta|prod ]]; then
        echo "ERROR: Script $0 requires environment argument"
        exit
fi

# if wa-internal envars needed, source file
if [[ -f ~/gitlab/ukwa-services-env/w3act/${ENVIRON}/w3act.env ]]; then
	source ~/gitlab/ukwa-services-env/w3act/${ENVIRON}/w3act.env
else
	echo "ERROR: wa-internal env file missing"
	exit
fi

# setup venv
#### venv created via 'virtualenv -p /usr/local/bin/python3.6 venv'
export PYTHONPATH=~/github/python-w3act
source $PYTHONPATH/venv/bin/activate
cd $PYTHONPATH

# ensure python libraries installed
pip install -r requirements.txt

# run script
./venv/bin/w3act-qa-check -m "lee.davey@bl.uk,gil.hoggarth@bl.uk" -f -c "-H ingest -P 5434 -U w3act -p ${W3ACT_PSQL_PASSWORD}" -d 300
#./venv/bin/w3act-qa-check -m "Carlos.Rarugal@bl.uk" -f -c "-H ingest -P 5434 -U w3act -p ${W3ACT_PSQL_PASSWORD}"
#./venv/bin/w3act-qa-check -m "Nicola.Bingham@bl.uk,Helena.Byrne@bl.uk" -c "-H ingest -P 5434 -U w3act -p ${W3ACT_PSQL_PASSWORD}"
