#!/usr/bin/env bash

# read script environ argument
ENVIRON=$1
if ! [[ ${ENVIRON} =~ dev|beta|prod ]]; then
        echo "ERROR: Script $0 requires environment argument"
        exit
fi

# if wa-internal envars needed, source file
if [[ -f ~/gitlab/ukwa-services-env/w3act/${ENVIRON}/w3act.env ]]; then
        source ~/gitlab/ukwa-services-env/w3act/${ENVIRON}/w3act.env
else
        echo "ERROR: wa-internal env file missing"
        exit
fi

# setup venv
#### venv created via 'virtualenv -p /usr/local/bin/python3.6 venv'
export PYTHONPATH=~/github/python-w3act
source $PYTHONPATH/venv/bin/activate
cd $PYTHONPATH

# ensure python libraries installed
pip install -r requirements.txt

# run script
if [[ ${ENVIRON} == 'dev' ]]; then
        ./venv/bin/w3act-qa-check -f -c "-H prod1 -P 5432 -p ${W3ACT_PSQL_PASSWORD}"
elif [[ ${ENVIRON} == 'beta' ]]; then
        ./venv/bin/w3act-qa-check -m "Gil.Hoggarth@bl.uk" -f -c "-H prod1 -P 5432 -p ${W3ACT_PSQL_PASSWORD}"
else
        ./venv/bin/w3act-qa-check -m "Carlos.Rarugal@bl.uk" -f -c "-H prod1 -P 5432 -p ${W3ACT_PSQL_PASSWORD}"
        ./venv/bin/w3act-qa-check -m "Nicola.Bingham@bl.uk" -c "-H prod1 -P 5432 -p ${W3ACT_PSQL_PASSWORD}"
fi
